(define (cube x) (* x x x))
(define (p x) (- (* 3 x) (* 4 (cube x))))
(define (sine angle)
   (if (not (> (abs angle) 0.1))
       angle
       (p (sine (/ angle 3.0)))))

(sine 12.15)
(p (sine 4.05))
(- (* 3 (sine 4.05)) (* 4 (cube (sine 4.05))))
(- (* 3 (p (sine 1.35))) (* 4 (cube (p (sine 1.35)))))
(- (* 3 (- (* 3 (sine 1.35)) (* 4 (cube (sine 1.35))))) (* 4 (cube (- (* 3 (sine 1.35)) (* 4 (cube (sine 1.35)))))))

(- (* 3 (- (* 3 (p (sine .45))) (* 4 (cube (p (sine .45))))))
   (* 4 (cube (- (* 3 (p (sine .45))) (* 4 (cube (p (sine .45))))))))

(- (* 3 (- (* 3 (- (* 3 (p (sine .15)))
                   (* 4 (cube (p (sine .15))))))
           (* 4 (cube (- (* 3 (p (sine .15)))
                         (* 4 (cube (p (sine .15)))))))))
   (* 4 (cube (- (* 3 (- (* 3 (p (sine .15)))
                         (* 4 (cube (p (sine .15))))))
                 (* 4 (cube (- (* 3 (p (sine .15)))
                               (* 4 (cube (p (sine .15)))))))))))

(- (* 3 (- (* 3 (- (* 3 (p (sine .15)))
                   (* 4 (cube (p (sine .15))))))
           (* 4 (cube (- (* 3 (p (sine .15)))
                         (* 4 (cube (p (sine .15)))))))))
   (* 4 (cube (- (* 3 (- (* 3 (p (sine .15)))
                         (* 4 (cube (p (sine .15))))))
                 (* 4 (cube (- (* 3 (p (sine .15)))
                               (* 4 (cube (p (sine .15)))))))))))